### ISSUE TITLE
add build.grade code and help how to use it?

### ISSUE THREAD

**Issue by tellfa** [worldline/FoldableLayout#1]
hi
tnx for this great library, but how can in use this? please help me and insert build.gradle code
such as :     compile 'com.android.support:appcompat-v7:22.2.1'

**Comment by vincentbrison** [comment]
Hi,
As said in the readme, this is for now not a proper library release on any maven repos. 
Also, as said in the readme :
> "this code is very much specific (even if it is working from a separate gradle module). This is more a showcase, and if you want to use it, I greatly recommend you to understand the code from the foldablelayout and adapt it to your usage."

So you can import the [gradle foldable layout module](https://github.com/worldline/FoldableLayout/tree/dev/foldablelayout) and use it in your application, as it is done in this showcase for the gradle `app` module.

You could also use https://jitpack.io/

However I may release the library on maven in the next days. But for now you should directly import it as a module in your project, to be able to customize the library to match your needs.
