### ISSUE TITLE
Error:(23, 14) Failed to resolve: com.vincentbrison.openlibraries.android:foldablelayout:0.0.1-SNAPSHOT

### ISSUE THREAD

**Issue by tianshaokai** [worldline/FoldableLayout#3]

**Comment by vincentbrison** [comment]
Hi,
What is your issue exactly ? I think you should pull this artifact com.vincentbrison.openlibraries.android:foldablelayout:0.0.1@aar. I dont think there is a snapshot avaialble right know and 0.0.1 is the last version available.

**Comment by vincentbrison** [comment]
Not enough information provided
