### ISSUE TITLE
What is this error and how to solve?

### ISSUE THREAD

**Issue by giul2016** [worldline/FoldableLayout#4]
Error:(23, 14) Failed to resolve: com.vincentbrison.openlibraries.android:foldablelayout:0.0.1-SNAPSHOT
<a href="openFile:C:/Users/giul/AndroidStudioProjects/FoldableLayout/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by vincentbrison** [comment]
Hi,
You should use compile `com.vincentbrison.openlibraries.android:foldablelayout:0.0.1@aar` from `mavenCentral` instead of  `com.vincentbrison.openlibraries.android:foldablelayout:0.0.1-SNAPSHOT` which is only use for dev purpose.
BR
