### ISSUE TITLE
Fold automatically previously opened cards.

### ISSUE THREAD

**Issue by gpt3ch** [worldline/FoldableLayout#6]
When we click on a card it unfolds, when we click on another card that too unfolds, how can the previously opened card be folded automatically so that at one time only one card remains unfolded?

**Comment by vincentbrison** [comment]
You need to keep a separate model to store the card fold / unfold states. It could be stored in a https://developer.android.com/reference/android/util/SparseBooleanArray.html for example. When you click on a card, you would store fold / unfold state in this array, and fold / unfold the cards you want based on the fold / unfold states.
